site_name: SQL Guide
use_directory_urls: true  # optional, default is true
site_url: https://andikatjacobdennis.github.io/SQL_Guide/
repo_url: https://github.com/andikatjacobdennis/SQL_Guide/  # ← Required for edit links to work
edit_uri: edit/main/docs/  # ← Required for edit links to work

# --- Theme Configuration ---
theme:
  name: material
  #custom_dir: overrides # Use a custom directory for advanced customizations (optional, but good for future)
  strict: true
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight # Added for better search experience
    - search.share
    - toc.follow
    - toc.expand
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.layout.wide
    - content.action.view # Added to allow viewing source on GitHub
    - content.code.copy
  palette:
    # Light theme (default)
    - scheme: default
      primary: light blue # Softer blue for a more modern feel
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark theme
    - scheme: slate
      primary: blue grey # A sophisticated dark primary
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Fira Code # Excellent choice for code readability

# --- Global Extras ---
extra:
  search:
    language: en
    pipeline: stemmer, stopword
    separator: '[\s\-\.]' # Added period as a separator for better search results
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andikatjacobdennis/SQL_Guide/ # Changed to the SQL Server repo link for direct relevance
    - icon: fontawesome/brands/linkedin # Added LinkedIn for professional presence
      link: https://www.linkedin.com/in/andikatjacobdennis/
  generator: false # Hide the "Built with MkDocs" footer for a cleaner look
  metadata:
    description: "Comprehensive SQL Server guide."
    keywords: "SQL, database, tutorial"

# --- Plugin Configuration ---
plugins:
  - search:
      lang: en
      separator: '[\s\-\.]' # Consistent with extra.search separator
  - mermaid2
  - tags
  - minify:
      minify_html: true
  - git-revision-date-localized # Displays last update date, adds professionalism
  # - blog # Consider adding if you plan to have a blog section
  - glightbox # For beautiful image lightboxes (if you have many images)

# --- Markdown Extensions ---
markdown_extensions:
  - pymdownx.highlight:
      linenums: true                # Enable line numbers
      anchor_linenums: true         # Allow linking to specific lines
      linenums_style: table         # Optional: clean 2-column layout
      use_pygments: true
      pygments_lang_class: true     # Adds language class for better styling
      pygments_style: monokai       # Other good options: 'dracula', 'native', 'solarized-dark'
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - admonition # Crucial for visually distinct notes, tips, warnings
  - pymdownx.emoji: # For emojis, enhancing readability and fun
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list # Allows adding classes/IDs to markdown elements
  - md_in_html # Allows Markdown within HTML blocks

nav:
  - Home: index.md
  - Getting Started with SQL Server: 001_Getting_Started_with_SQL_Server/index.md

# --- Assets ---
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css # Latest Font Awesome CDN for more icons

# extra_javascript:
#   - javascripts/extra.js # Uncomment if you have custom JS

# --- Copyright ---
copyright: "&copy; 2025 Andikat Jacob Dennis. All rights reserved." # More professional copyright format